#!/usr/bin/env python

from sys import argv
from docx import Document
from transform_to_xml import convert_monster_text_to_xml

def lire_fichier_word(chemin_fichier):
    doc = Document(chemin_fichier)
    texte = []

    for paragraphe in doc.paragraphs:
        texte.append(paragraphe.text)

    return '\n'.join(texte)

if __name__ == "__main__":
    if len(argv) < 2 :
        print("Not enough arguments")
        exit(0)
    texte_extrait = lire_fichier_word(argv[1])
    convert_monster_text_to_xml(texte_extrait)
    # print("Texte extrait du fichier Word :\n")
