version: '3.8'

services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'mannheim'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'root'
        ports:
            - '3306:3306'
        volumes:
            - db:/var/lib/mysql
            - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
        networks:
            - mannheim

    server:
        build:
            context: ./back
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            db:
                condition: service_started
        networks:
            - mannheim

    mobile:
        build:
            context: ./mobile
            dockerfile: Dockerfile
            args:
                VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        ports:
            - "8082:80"
        networks:
            - mannheim
        environment:
            - NODE_ENV=production
        ulimits:
            nofile:
                soft: 5000
                hard: 5000
        volumes:
            - 'apk:/shared'

    frontend:
        build:
            context: ./front
            dockerfile: Dockerfile
            args:
                VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        ports:
            - "8081:80"
        depends_on:
            mobile:
                condition: service_completed_successfully
            server:
                condition: service_started
        networks:
            - mannheim
        volumes:
            - 'apk:/shared'

networks:
    mannheim:
        driver: bridge

volumes:
    db:
    apk:
        driver: local
