export const dico: { [key: string]: string }  = {
    name: "Nom",
    race: "Espèce",
    age: "Age",
    priority: "Priorité",
    attributes: "Attributs",
    resistance: "Résistance",
    strength: "Force",
    agility: "Agilité",
    dexterity: "Dextérité",
    vivacity: "Vivacité",
    social: "Social",
    role: "Rôle",
    competencies: "Compétences",
    ranged: "Combat à distance",
    bow: "Arc",
    crossbow: "Arbalète",
    exoticWeapon: "Arme exotique",
    smallProjectile: "Petit projectile",
    pistol: "Pistolet",
    artillery: "Artillerie",
    cannon: "Canon",
    engine: "Engin",
    melee: "Corps à corps",
    polearm: "Arme d'hast",
    blunt: "Contondante",
    shortBlade: "Courte lame",
    sword: "Epée",
    axe: "Hache",
    saber: "Sabre",
    bareHands: "Main nue",
    protective: "Protectrice",
    shield: "Bouclier",
    movement: "Déplacement",
    acrobatics: "Acrobatie",
    running: "Course",
    balance: "Equilibre",
    riding: "Equitation",
    climbing: "Escalade",
    dodging: "Esquive",
    swimming: "Nage",
    navigation: "Navigation",
    landing: "Réception",
    jumping: "Saut",
    endurance: "Endurance",
    mental: "Mentale",
    pathological: "Pathologique",
    physical: "Physique",
    survival: "Survie",
    lockpicking: "Crochetage",
    stealth: "Discrétion",
    manipulation: "Manipulation",
    orientalKnowledge: "Orientation",
    fishing: "Pêche",
    tracking: "Pistage",
    reflex: "Réflexe",
    lifting: "Soulèvement",
    taming: "Dressage",
    deceit: "Imposture",
    intimidation: "Intimidation",
    speech: "Parole",
    persuasion: "Persuasion",
    psychology: "Psychologie",
    intellect: "Intellect",
    knowledge: "Connaissance",
    anatomy_knowledge: "Anatomique",
    artistic_knowledge: "Artistique",
    astronomy_knowledge: "Astronomique",
    biology_knowledge: "Biologique",
    cultural_knowledge: "Culturel",
    geography_knowledge: "Géographique",
    warfare_knowledge: "Guerrière",
    history_knowledge: "Historique",
    linguistics_knowledge: "Linguistique",
    magic_knowledge: "Magie",
    mysticism_knowledge: "Mystique",
    technology_knowledge: "Technologique",
    concentration: "Concentration",
    deduction: "Déduction",
    memory: "Mémoire",
    observation: "Observation",
    craft: "Artisanat",
    visualArts: "Art plastique",
    chemistry: "Chimie",
    construction: "Construction",
    cooking: "Cuisine",
    explosives: "Explosif",
    forging: "Forge",
    medecine: "Médecine",
    music: "Musique",
    alchemy: "Alchimie",
    enhancement: "Amélioration",
    envoutment: "Envoûtement",
    annihilation: "Annihilation",
    conjuration: "Conjuration",
    elementarism: "Élémentarisme",
    enchantment: "Enchantement",
    illusionism: "Illusionnisme",
    summoning: "Invocation",
    necromancy: "Nécromancie",
    perception: "Perception",
    sealing: "Scellement",
    witchcraft: "Sorcellerie",
    absorption: "Absorption",
    mana: "Mana",
    languages: "Langues",
    totemAnimals: "Animaux totems",
    religions: "Religions",
    god: "Dieu",
    devotion: "Piété",
    animals: "Animaux",
    inventory: "Inventaire",
    weight: "Poids",
    contents: "Contenu",
    money: "Monnaie",
    skills: "Compétences",
    attribute: "Attribut",
}